{% set version = "2.1.3" %}

package:
  name: gdal
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
  sha256: ae6a0a0dc6eb45a981a46db27e3dfe16c644fcf04732557e2cb315776974074a
  patches:
    - clang.patch  # [osx]
    - prepend-dll.patch  # [win]
    # Fixes compilation problems with JPEG.
    # https://lists.osgeo.org/pipermail/gdal-dev/2016-January/043443.html
    - disable_jpeg12.patch  # [win]
    - windowshdf5.patch  # [win]
    - multiprocessor.patch  # [win]
    - install_scripts.patch

build:
  number: 5
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python
    # Must be 3.0.8
    # see https://github.com/conda-forge/gdal-feedstock/issues/131
    - swig 3.0.8
    - sed  # [osx]
    - setuptools
    - cmake  # [win]
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - hdf4
    - hdf5 1.8.18|1.8.18.*
    - geos 3.5.1
    - proj4 4.9.3
    - xerces-c
    - libnetcdf 4.4.*
    - libdap4 3.18.*  # [not win]
    - kealib
    - libtiff 4.0.*
    - libpng >=1.6.28,<1.7
    - zlib 1.2.8  # [not win]
    - jpeg 9*
    - postgresql
    - giflib 5.1.*  # [not win]
    - json-c  # [not win]
    - freexl
    - openjpeg
    - curl
    - expat
    - sqlite 3.13.*
    - libspatialite
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - hdf4
    - hdf5 1.8.18|1.8.18.*
    - geos 3.5.1
    - proj4 4.9.3
    - xerces-c
    - libnetcdf 4.4.*
    - libdap4 3.18.*  # [not win]
    - kealib
    - libtiff 4.0.*
    - libpng >=1.6.28,<1.7
    - zlib 1.2.8  # [not win]
    - jpeg 9*
    - libpq
    - giflib 5.1.*  # [not win]
    - json-c  # [not win]
    - freexl
    - openjpeg
    - curl
    - expat
    - sqlite 3.13.*
    - libspatialite
    - pcre
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]

test:
  files:
    - test_data
    - extra_tests.py
  imports:
    - osr
    - gdal
    - gdalconst
    - osgeo
    - osgeo.ogr
    - osgeo.gdal
    - osgeo._gdal
    - osgeo._gdalconst
    - osgeo._ogr
    - osgeo._osr
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    - conda inspect linkages -p $PREFIX gdal  # [not win]
    - conda inspect objects -p $PREFIX gdal  # [osx]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'The Geospatial Data Abstraction Library (GDAL).'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
